### ISSUE TITLE
argument ... doesn't work in plot functions

### ISSUE THREAD

**Issue by caijun** [bjornsta/ncf#7]
Following code reproduces the issue.
```
# first generate some sample data
x <- expand.grid(1:20, 1:5)[, 1]
y <- expand.grid(1:20, 1:5)[, 2]
# z data from an exponential random field
z <- cbind(
  rmvn.spa(x = x, y = y, p = 2, method = "exp"),
  rmvn.spa(x = x, y = y, p = 2, method = "exp")
)

# Spatial correlogram
fit1 <- correlog(x = x, y = y, z = z[, 1], increment = 2, resamp = 0)
plot(fit1)
plot(fit1, main = "Change title") # the plot title doesn't change
```
I will fix this issue.

**Comment by caijun** [comment]
Now `plot(fit1)` produces following plot

![image](https://user-images.githubusercontent.com/2522593/38974593-53a9c348-43dd-11e8-9fdd-ef095d23c2b0.png)

We can change the plot title and x-axis label by specifying the `main = "Change title"`  and `xlab = "Change xlab` arguments thanks to the `...` argument.

![image](https://user-images.githubusercontent.com/2522593/38980683-1348ae96-43f0-11e8-8633-705a45604b43.png)

**Comment by caijun** [comment]
Moreover, the arguments `xmax = 0` and `ylim = c(-1, 1)` of function `plot.Sncf()` can be omitted as we can specify them by the argument `...`. Omitting these two arguments can make `plot.Sncf()` function simple and flexible, and the documentation shorter. Do you think those changes are necessary? @bjornsta

**Comment by objornstad** [comment]
These are very useful changes. I never understood how "..." was passed on. Many of the other plot-functions can probably similarly be improved.
